name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # SETUP
      - uses: actions/checkout@v2

      - uses: thomashoneyman/setup-purescript@main
        with:
          purescript: "0.13.8"
          spago: "0.15.3"
          zephyr: "0.3.2"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output/[!CategoryBox]*
            output/[!Main]

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install npm modules
        run: npm install

      # BUILD
      - name: Build source
        run: spago build

      # PREBUILD
      - name: Prebuild
        run: npm run prebuild

      # DEPLOY
      - name: Run bundle
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist